### ISSUE TITLE
Update LICENSE.md

### ISSUE THREAD

**Issue by ondrj** [ichlubna/mind#2]
Hey,

thanks for adding license.
Nevertheless, besides of copyright, would you mind to add some more permissive license (e.g. one of the BSD/GPL family)?

I'm seriously considering to fork the project and re-write it completely from scratch with the use of native languages (using all advantages of APIs of given SDKs), mainly for JVM.

I do not plan to monetize the app in any way.

Thanks,

Ondrej

**Comment by ichlubna** [comment]
@ondrj Why would you do all the work? Please be careful because all the content in this app had been consulted with specialists and any modifications might be dangerous for potential users with mental disorders. Also as stated in the licence, the images from Anabell are copyrighted.

**Comment by ondrj** [comment]
Content (i.e. information) would stay the same, I will just re-write app using the best practices I have learned in mobile development. I don't think that Qt is suitable solution for mobile development in the first place.
Then, the potential new features would be easily scalable. Sorry for being honest, but this reminds me semi-finished MVP to be fair (given quality of code and the lack of features).
Also I can understand the scope of issues this app is trying to solve, because I'm fighting with clinical depression & anxiety for more than 16 years.
Nevertheless the final decision is up to you.

**Comment by ichlubna** [comment]
@ondrj As you wish but we don't intend to leave Qt, sorry. Qt is simple and easy to maintain multi-platform solution and this application doesn't need any special optimizations or performance boosts so no reason to use native API. 
The code quality is not optimal mainly because of the time pressure. Hopefully will change in the future. 
So while we appreciate your good intention please don't expect us to adopt your solution. Thanks anyway.
