### ISSUE TITLE
Possible troubles in editing and saving Activities, What made me happy e.t.c.

### ISSUE THREAD

**Issue by JanKMinar** [ichlubna/mind#3]
There may be some mistakes in the editor of the items in "Activity planner", "What made me happy" etc. as follows:
1.	it is not clear how to save a newly created “activity” or “happy item” to let it remain till the next restart of the application; they simply seem to be getting deleted.
2.	when editing a new application with SwiftKey keyboard, keys “Enter” and “Back Space” do not work properly at my Android phone.

**Comment by ichlubna** [comment]
Yes thanks for the report. We've noticed that a few days ago. The new update (coming on gplay probably this week) shall fix the first issue. Should be OK in bb1f675e91a01ec6ea54beaa6624f0ffdb022226. 

The problem was that we've added a functionality to translate the default inputs in those sections which however contained a bug. Please let me know if you still see the problem after update.

The second one will be fixed soon as well hopefully! The edited text should be fine when you hit the system back button after editing the text.
